name = "music-api"
main = "./src/index.ts"
compatibility_date = "2024-05-01"

# 环境变量
[vars]
# 用于签发/验证 JWT 的密钥，请在 Dashboard 中改为真实随机值
JWT_SECRET = "REPLACE_WITH_SECURE_RANDOM_STRING"
GITHUB_CLIENT_ID = "YOUR_GITHUB_CLIENT_ID"
GITHUB_CLIENT_SECRET = "YOUR_GITHUB_CLIENT_SECRET"

# 绑定 D1 数据库
[[d1_databases]]
binding = "DB"          # 在 Worker 代码中通过 env.DB 访问
database_name = "melodysync-db"
database_id = "ac2bcba3-b99d-40aa-ac99-9ea1d7f36210"

# 绑定 KV 命名空间（存 session / 验证码等）
[[kv_namespaces]]
binding = "SESSIONS"
id = "03253adbeadf4b159a4558b3cc991b4f"